# .github/workflows/ci.yml

name: Vue.js CI/CD (Lint & Build)

on:
  pull_request:
    branches: [ master ]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install


      - name: Run Lint and Type Check
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/
          if-no-files-found: error